name: Daily ELO Calculation

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 12 * * *'  # Runs every day at 12 PM UTC
  
jobs:
  elo_calculation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Create Firebase query JSON
      id: firebase-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: servicekey_admin.json
        json: ${{ secrets.FIREBASE_SERVICE_KEY_JSON }}

    - name: Install dependencies
      run: |
        pip install -r backend/elo_requirements.txt 

    - name: Run ELO calculations
      run: |
        python backend/elo_calculations.py

    - name: Commit and push results
      run: |
        git config --local user.email "adityamittal307@gmail.com"
        git config --local user.name "Aditya Mittal"
        git add backend/leaderboard.csv
        git commit -m "Update ELO results"
        git push https://adityamittal13:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/adityamittal13/codearenawebsite.git